version: '3'
services:
  backend:
    build:
      context: ./Application
      dockerfile: Dockerfile
    ports:
      - "4005:80"

  frontendapp:
    build:
      context: ./patient-management-app
      dockerfile: Dockerfile
    ports:
      - "4010:80"
