version: '3'
services:
  backend:
    build:
      context: ./Application
      dockerfile: Dockerfile
    ports:
      - "4005:80"
    environment:
      - ConnectionStrings__DbString=Server=host.docker.internal;Database=patientDatabase;uid=root;pwd=@4Islamabad$

  frontendapp:
    build:
      context: ./patient-management-app
      dockerfile: Dockerfile
    ports:
      - "4010:80"
