version: '3'
services:
  backend:
    build:
      context: ./Application
      dockerfile: Dockerfile
    ports:
      - "3500:80"

  frontendapp:
    build:
      context: ./patient-management-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
